name: Receiver
 
on:
  repository_dispatch:
    types: [trigger_workflow]
 
jobs:
  receiver:
    runs-on: ubuntu-latest
    steps:
      - name: A event received
        run: |
          echo "This Workflow got triggered from this repo: https://github.com/ujala-singh/packer-ansible-aws."
