name: Receiver
 
on:
  repository_dispatch:
    types: [trigger_workflow]
 
jobs:
  receiver:
    runs-on: ubuntu-latest
    steps:
      - name: An event received
        env:
          REPO_NAME: ${{ github.event.client_payload.repo.name }}
          BRANCH_NAME: ${{ github.event.client_payload.repo.branch }}
        run: |
          echo "This Workflow got triggered from the repo: https://github.com/$REPO_NAME and branch: $BRANCH_NAME."

      # Checkout branch.
      - name: Checkout to ${{ github.event.client_payload.repo.branch }} branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.repo.branch }}

      - name: run ls command
        run: |
          ls -la
