name: Receiver
 
on:
  repository_dispatch:
    types: [trigger_workflow]
 
jobs:
  receiver:
    runs-on: ubuntu-latest
    steps:
      - name: A event received
        run: |
          echo "payload Foo '${{ github.event.client_payload.foo }}'"
